name: .NET

on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --logger "trx;LogFileName=test-results.trx"
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Unit Test Results            # Name of the check run which will be created
        path: ${{ github.workspace }}/DemoWebApi.Test/TestResults/test-results.trx   # Path to test results
        reporter: dotnet-trx        # Format of test results
